### ISSUE TITLE
Coverage to 100

### ISSUE THREAD

**Issue by jaspercooper** [DeclareDesign/DesignLibrary#109]

**Comment by jaspercooper** [comment]
I get a weird error when I run `covr::package_coverage()`. Basically it doesn't work with the multi_arm designer -- even though it passes checks and tests using devtools.

My suspicion is that it has something to do with the environment in which the eval(parse()) call is evaluated during testing. This *might* explain what is going wrong with Windows too.

Any thoughts would be appreciated here as I try to increase test coverage.

**Comment by medinali** [comment]
I implemented a version of  multi_arm with rlang (in branch check_lm) it's not great yet but it will be! 

The package builds and tests are passing when I run comand devtools::test(), but, when I run devtools::checks() I get the an error for ALL designers similar to the following.

` Error: block_cluster_two_arm_designer's default design runs. (@test_designers.R#36) 
`

It's the same old error I've been getting when I run tests in Windows -- I think it's something related to devtools and 'keep.source' because when I run the built in Rstudio checks which runs the line below in the terminal things work pretty well -- only get two notes related to multi_arm.


`Rcmd.exe check --install-args="--with-keep.source" DesignLibrary_0.1.0.tar.gz`


Now, after doing this and running covr::package_coverage() I get coverage to 99% (multi_arm is what's keeping us away from 100%).
